apigateway:
  build: ./customer-service
  extends:
    file: docker-compose-common.yml
    service: javaserviceconfig
  ports:
    - "8081:808"
  links:
    - kafka
    - zookeeper
    - mysql

customerservice:
  build: ./customer-service
  extends:
    file: docker-compose-common.yml
    service: javaserviceconfig
  ports:
    - "8081:808"
  links:
    - kafka
    - zookeeper
    - mysql

accountservice:
  build: ./account-service
  extends:
    file: docker-compose-common.yml
    service: javaserviceconfig
  ports:
    - "8082:8082"
  links:
    - kafka
    - zookeeper
    - mysql
    - customerservice
  environment:
     CUSTOMER_SERVICE_URL: http://customerservice:8080/api/customers

moneytransferservice:
  build: ./money-transfer-service
  extends:
    file: docker-compose-common.yml
    service: javaserviceconfig
  ports:
     - "8083:8080"
  links:
    - kafka
    - zookeeper
    - mysql
    - accountservice
  environment:
    CUSTOMER_SERVICE_URL: http://accountservice:8080/api/accounts
