eureka:
  build: ./eureka-server
  ports:
    - "8761:8761"

mongodb:
  image: mongo:3.0.4
  command: --smallfiles --master
  ports:
    - "27017:27017"


zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.6.0
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: eventuateio/eventuateio-local-kafka:0.6.0
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  image: eventuateio/eventuateio-local-mysql:0.6.0
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw


cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.6.0
  extends:
    file: docker-compose-common.yml
    service: javaserviceconfig
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper


